title: GignLearn
description: Fun & Educational Hub for Kids!
theme: jekyll-theme-cayman

# This tells GitHub which pages to put in the top menu
header_pages:
  - index.md
  - blog.md
  - games.md
  - tools.md
  - printables.md
  - videos.md
  - about.md
