title: GignLearn
description: Fun & Educational Hub for Kids!
theme: jekyll-theme-cayman # A bold, colorful starting theme
show_downloads: false
google_analytics: # We can add your ID later for AdSense prep

